// This C++ source file was generated by the TTCN-3 compiler
// of the TTCN-3 Test Executor version CRL 113 200/6 R1A
// for Yann Garcia (yann@Ubuntu64) on Tue Feb 28 11:22:00 2017

// Copyright (c) 2000-2017 Ericsson Telecom AB

// Do not edit this file unless you know what you are doing.

/* Including header files */

#include "Btp_Templates.hh"

namespace Btp__Templates {

/* Prototypes of static functions */

static void pre_init_module();
static void post_init_module();

/* Literal string constants */

static const unsigned char module_checksum[] = { 0x96, 0xf8, 0xaa, 0xb3, 0x81, 0x03, 0xc5, 0xa5, 0xf9, 0xc8, 0x99, 0x71, 0xf5, 0x7d, 0x9e, 0x28 };

/* Global variable definitions */

static OCTETSTRING_template template_mw__frame_p__data__length_defval;
const OCTETSTRING_template& mw__frame_p__data__length_defval = template_mw__frame_p__data__length_defval;
static OCTETSTRING_template template_mw__frame_p__data__stream_defval;
const OCTETSTRING_template& mw__frame_p__data__stream_defval = template_mw__frame_p__data__stream_defval;
TTCN_Module module_object("Btp_Templates", __DATE__, __TIME__, module_checksum, pre_init_module, NULL, 0U, 4294967295U, 4294967295U, 4294967295U, NULL, 0LU, 0, post_init_module, NULL, NULL, NULL, NULL, NULL, NULL);

static const RuntimeVersionChecker ver_checker(  current_runtime_version.requires_major_version_6,
  current_runtime_version.requires_minor_version_1,
  current_runtime_version.requires_patch_level_0,  current_runtime_version.requires_runtime_2);

/* Bodies of functions, altsteps and testcases */

Btp__TestSystem::BtpInd_template mw__btpInd(const Btp__TypesAndValues::BtpPacket_template& p__btpPkt)
{
TTCN_Location current_location("../ttcn/Btp_Templates.ttcn", 8, TTCN_Location::LOCATION_TEMPLATE, "mw_btpInd");
Btp__TestSystem::BtpInd_template ret_val;
ret_val.msgIn() = p__btpPkt;
return ret_val;
}

Btp__TypesAndValues::BtpPacket_template mw__btpA(const INTEGER_template& p__destPort, const INTEGER_template& p__srcPort, const Btp__TypesAndValues::BtpPayload_template& p__payload)
{
TTCN_Location current_location("../ttcn/Btp_Templates.ttcn", 24, TTCN_Location::LOCATION_TEMPLATE, "mw_btpA");
Btp__TypesAndValues::BtpPacket_template ret_val;
{
Btp__TypesAndValues::BtpAHeader_template& tmp_0 = ret_val.header().btpAHeader();
tmp_0.destinationPort() = p__destPort;
tmp_0.sourcePort() = p__srcPort;
}
ret_val.payload() = p__payload;
return ret_val;
}

Btp__TypesAndValues::BtpPacket_template mw__btpB(const INTEGER_template& p__destPort, const INTEGER_template& p__destPortInfo, const Btp__TypesAndValues::BtpPayload_template& p__payload)
{
TTCN_Location current_location("../ttcn/Btp_Templates.ttcn", 44, TTCN_Location::LOCATION_TEMPLATE, "mw_btpB");
Btp__TypesAndValues::BtpPacket_template ret_val;
{
Btp__TypesAndValues::BtpBHeader_template& tmp_1 = ret_val.header().btpBHeader();
tmp_1.destinationPort() = p__destPort;
tmp_1.destinationPortInfo() = p__destPortInfo;
}
ret_val.payload() = p__payload;
return ret_val;
}

Btp__TypesAndValues::Frame_template mw__frame(const OCTETSTRING_template& p__data__length, const OCTETSTRING_template& p__data__stream)
{
TTCN_Location current_location("../ttcn/Btp_Templates.ttcn", 58, TTCN_Location::LOCATION_TEMPLATE, "mw_frame");
Btp__TypesAndValues::Frame_template ret_val;
ret_val.data__length() = p__data__length;
ret_val.data__stream() = p__data__stream;
return ret_val;
}


/* Bodies of static functions */

static void pre_init_module()
{
TTCN_Location current_location("../ttcn/Btp_Templates.ttcn", 0, TTCN_Location::LOCATION_UNKNOWN, "Btp_Templates");
Btp__TestSystem::module_object.pre_init_module();
}

static void post_init_module()
{
TTCN_Location current_location("../ttcn/Btp_Templates.ttcn", 0, TTCN_Location::LOCATION_UNKNOWN, "Btp_Templates");
Btp__TestSystem::module_object.post_init_module();
template_mw__frame_p__data__length_defval = ANY_VALUE;
template_mw__frame_p__data__stream_defval = ANY_VALUE;
}


} /* end of namespace */
