// This C++ source file was generated by the TTCN-3 compiler
// of the TTCN-3 Test Executor version CRL 113 200/6 R1A
// for Yann Garcia (yann@Ubuntu64) on Tue Feb 28 11:22:01 2017

// Copyright (c) 2000-2017 Ericsson Telecom AB

// Do not edit this file unless you know what you are doing.

/* Including header files */

#include "Btp_TestControl.hh"

namespace Btp__TestControl {

/* Prototypes of static functions */

static void pre_init_module();
static void post_init_module();
static void module_control_part();

/* Literal string constants */

static const unsigned char module_checksum[] = { 0xa7, 0x11, 0xc3, 0xcd, 0x57, 0x9f, 0xe5, 0x02, 0x78, 0x0a, 0x74, 0xc8, 0xe3, 0xe4, 0xea, 0x3a };

/* Global variable definitions */

TTCN_Module module_object("Btp_TestControl", __DATE__, __TIME__, module_checksum, pre_init_module, NULL, 0U, 4294967295U, 4294967295U, 4294967295U, NULL, 0LU, 0, post_init_module, NULL, NULL, NULL, NULL, NULL, module_control_part);

static const RuntimeVersionChecker ver_checker(  current_runtime_version.requires_major_version_6,
  current_runtime_version.requires_minor_version_1,
  current_runtime_version.requires_patch_level_0,  current_runtime_version.requires_runtime_2);

/* Bodies of static functions */

static void pre_init_module()
{
TTCN_Location current_location("../ttcn/Btp_TestControl.ttcn", 0, TTCN_Location::LOCATION_UNKNOWN, "Btp_TestControl");
Btp__TestCases::module_object.pre_init_module();
}

static void post_init_module()
{
TTCN_Location current_location("../ttcn/Btp_TestControl.ttcn", 0, TTCN_Location::LOCATION_UNKNOWN, "Btp_TestControl");
Btp__TestCases::module_object.post_init_module();
}

static void module_control_part()
{
TTCN_Location current_location("../ttcn/Btp_TestControl.ttcn", 5, TTCN_Location::LOCATION_CONTROLPART, "Btp_TestControl");
TTCN_Runtime::begin_controlpart("Btp_TestControl");
current_location.update_lineno(7);
/* ../ttcn/Btp_TestControl.ttcn, line 7 */
Btp__TestCases::testcase_TC__BTP__PGA__BV__01(FALSE, 0.0);
TTCN_Runtime::end_controlpart();
}


} /* end of namespace */
