// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/6 R1A
// for Ubuntu (ubuntu@ubuntu-xenial) on Fri May  5 14:11:24 2017

// Copyright (c) 2000-2017 Ericsson Telecom AB

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "UtPort.hh"

#include "loggers.hh"

namespace MyExample {

UtPort::UtPort(const char *par_port_name)
	: UtPort_BASE(par_port_name)
{
    loggers::loggers::log("UtPort::UtPort");
}

UtPort::~UtPort()
{
    loggers::loggers::log("UtPort::~UtPort");
}

void UtPort::set_parameter(const char * parameter_name,
	const char * parameter_value)
{
    loggers::loggers::log("UtPort::set_parameter (%s, %s)", parameter_name, parameter_value);
}

/*void UtPort::Handle_Fd_Event(int fd, boolean is_readable,
	boolean is_writable, boolean is_error) {}*/

void UtPort::Handle_Fd_Event_Error(int /*fd*/)
{

}

void UtPort::Handle_Fd_Event_Writable(int /*fd*/)
{

}

void UtPort::Handle_Fd_Event_Readable(int /*fd*/)
{

}

/*void UtPort::Handle_Timeout(double time_since_last_call) {}*/

void UtPort::user_map(const char * system_port)
{
    loggers::loggers::log("UtPort::user_map %s", system_port);
}

void UtPort::user_unmap(const char * system_port)
{
    loggers::loggers::log("UtPort::user_unmap %s", system_port);
}

void UtPort::user_start()
{

}

void UtPort::user_stop()
{

}

void UtPort::outgoing_send(const UtInitialise& /*send_par*/)
{
    loggers::loggers::log("UtPort::outgoing_send");
}

} /* end of namespace */

